version: '3.3'

services:

  freeipa:
    image: freeipa/freeipa-server:rocky-8
    restart: unless-stopped
    tty: true
    stdin_open: true
    hostname: ipa
    domainname: lan
    extra_hosts:
      - "ipa.lan:192.168.1.3"
    environment:
      - IPA_SERVER_HOSTNAME=ipa.lan
      - IPA_SERVER_IP=192.168.1.3
      - DNS=192.168.1.1
      - TZ=America/Edmonton
    command:
      - ipa-server-install
      - --realm=lan
      - --domain=lan
      - --ds-password=xxxxxxxxxx
      - --admin-password=xxxxxxxxxx
      - --no-host-dns
      - --setup-dns
      - --auto-forwarders
      - --allow-zone-overlap
      - --no-dnssec-validation
      - --unattended
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./data:/data
      - ./logs:/var/logs
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /var/cache
      - /tmp
    cap_add:
      - SYS_TIME
    ports:
      - "192.168.1.3:80:80/tcp"
      - "192.168.1.3:443:443/tcp"
      # DNS
      - "192.168.1.3:53:53/tcp"
      - "192.168.1.3:53:53/udp"
      # LDAP(S)
      - "192.168.1.3:389:389/tcp"
      - "192.168.1.3:636:636/tcp"
      # Kerberos
      - "192.168.1.3:88:88/tcp"
      - "192.168.1.3:464:464/tcp"
      - "192.168.1.3:88:88/udp"
      - "192.168.1.3:464:464/udp"
