db_data  docker-compose.yaml  html
root@docker:/docker/wordpress# cat docker-compose.yaml 
services:
  mariadb:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpresspw
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress
    ports:
      - 8000:80
    volumes:
      - ./html:/var/www/html
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpresspw
volumes:
  db_data: