version: '3'
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8080:8000
    volumes:
      - /docker/yacht/config:/config
      - /docker/yacht/compose:/compose
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht:devel
    environment:
      - DISABLE_AUTH=true
      - COMPOSE_DIR=/compose
volumes:
  yacht:
